// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


var standard_library = "/Users/javi/Development/github/bucklescript/vendor/ocaml/lib/ocaml";

exports.standard_library = standard_library;
/* No side effect */
