// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Hashtbl = require("bs-platform/lib/js/hashtbl.js");
var Parsing = require("bs-platform/lib/js/parsing.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Location$Jeason = require("./location.bs.js");
var Warnings$Jeason = require("./warnings.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var docstrings = [/* [] */0];

function warn_bad_docstrings() {
  if (Warnings$Jeason.is_active(/* Bad_docstring */Block.__(33, [/* true */1]))) {
    return List.iter((function (ds) {
                  var match = ds[/* ds_attached */2];
                  switch (match) {
                    case 0 : 
                        return Location$Jeason.prerr_warning(ds[/* ds_loc */1], /* Bad_docstring */Block.__(33, [/* true */1]));
                    case 1 : 
                        return /* () */0;
                    case 2 : 
                        var match$1 = ds[/* ds_associated */3];
                        if (match$1 >= 2) {
                          return Location$Jeason.prerr_warning(ds[/* ds_loc */1], /* Bad_docstring */Block.__(33, [/* false */0]));
                        } else {
                          return /* () */0;
                        }
                    
                  }
                }), List.rev(docstrings[0]));
  } else {
    return 0;
  }
}

function docstring(body, loc) {
  var ds = /* record */[
    /* ds_body */body,
    /* ds_loc */loc,
    /* ds_attached : Unattached */0,
    /* ds_associated : Zero */0
  ];
  docstrings[0] = /* :: */[
    ds,
    docstrings[0]
  ];
  return ds;
}

function docstring_body(ds) {
  return ds[/* ds_body */0];
}

function docstring_loc(ds) {
  return ds[/* ds_loc */1];
}

var doc_loc = /* record */[
  /* txt */"ocaml.doc",
  /* loc */Location$Jeason.none
];

function docs_attr(ds) {
  var exp_000 = /* pexp_desc : Pexp_constant */Block.__(1, [/* Const_string */Block.__(2, [
          ds[/* ds_body */0],
          /* None */0
        ])]);
  var exp_001 = /* pexp_loc */ds[/* ds_loc */1];
  var exp = /* record */[
    exp_000,
    exp_001,
    /* pexp_attributes : [] */0
  ];
  var item_000 = /* pstr_desc : Pstr_eval */Block.__(0, [
      exp,
      /* [] */0
    ]);
  var item_001 = exp_001;
  var item = /* record */[
    item_000,
    item_001
  ];
  return /* tuple */[
          doc_loc,
          /* PStr */Block.__(0, [/* :: */[
                item,
                /* [] */0
              ]])
        ];
}

function add_docs_attrs(docs, attrs) {
  var match = docs[/* docs_pre */0];
  var attrs$1 = match ? /* :: */[
      docs_attr(match[0]),
      attrs
    ] : attrs;
  var match$1 = docs[/* docs_post */1];
  if (match$1) {
    return Pervasives.$at(attrs$1, /* :: */[
                docs_attr(match$1[0]),
                /* [] */0
              ]);
  } else {
    return attrs$1;
  }
}

function add_info_attrs(info, attrs) {
  if (info) {
    return Pervasives.$at(attrs, /* :: */[
                docs_attr(info[0]),
                /* [] */0
              ]);
  } else {
    return attrs;
  }
}

var text_loc = /* record */[
  /* txt */"ocaml.text",
  /* loc */Location$Jeason.none
];

function text_attr(ds) {
  var exp_000 = /* pexp_desc : Pexp_constant */Block.__(1, [/* Const_string */Block.__(2, [
          ds[/* ds_body */0],
          /* None */0
        ])]);
  var exp_001 = /* pexp_loc */ds[/* ds_loc */1];
  var exp = /* record */[
    exp_000,
    exp_001,
    /* pexp_attributes : [] */0
  ];
  var item_000 = /* pstr_desc : Pstr_eval */Block.__(0, [
      exp,
      /* [] */0
    ]);
  var item_001 = exp_001;
  var item = /* record */[
    item_000,
    item_001
  ];
  return /* tuple */[
          text_loc,
          /* PStr */Block.__(0, [/* :: */[
                item,
                /* [] */0
              ]])
        ];
}

function add_text_attrs(dsl, attrs) {
  return Pervasives.$at(List.map(text_attr, dsl), attrs);
}

function get_docstring(info, dsl) {
  var _param = dsl;
  while(true) {
    var param = _param;
    if (param) {
      var ds = param[0];
      var match = ds[/* ds_attached */2];
      if (match !== 1) {
        ds[/* ds_attached */2] = info ? /* Info */1 : /* Docs */2;
        return /* Some */[ds];
      } else {
        _param = param[1];
        continue ;
        
      }
    } else {
      return /* None */0;
    }
  };
}

function get_docstrings(dsl) {
  var _acc = /* [] */0;
  var _param = dsl;
  while(true) {
    var param = _param;
    var acc = _acc;
    if (param) {
      var ds = param[0];
      var match = ds[/* ds_attached */2];
      if (match !== 1) {
        ds[/* ds_attached */2] = /* Docs */2;
        _param = param[1];
        _acc = /* :: */[
          ds,
          acc
        ];
        continue ;
        
      } else {
        _param = param[1];
        continue ;
        
      }
    } else {
      return List.rev(acc);
    }
  };
}

function associate_docstrings(dsl) {
  return List.iter((function (ds) {
                var match = ds[/* ds_associated */3];
                if (match !== 0) {
                  ds[/* ds_associated */3] = /* Many */2;
                  return /* () */0;
                } else {
                  ds[/* ds_associated */3] = /* One */1;
                  return /* () */0;
                }
              }), dsl);
}

var pre_table = Hashtbl.create(/* None */0, 50);

function set_pre_docstrings(pos, dsl) {
  if (dsl !== /* [] */0) {
    return Hashtbl.add(pre_table, pos, dsl);
  } else {
    return 0;
  }
}

function get_pre_docs(pos) {
  try {
    var dsl = Hashtbl.find(pre_table, pos);
    associate_docstrings(dsl);
    return get_docstring(/* false */0, dsl);
  }
  catch (exn){
    if (exn === Caml_builtin_exceptions.not_found) {
      return /* None */0;
    } else {
      throw exn;
    }
  }
}

function mark_pre_docs(pos) {
  try {
    return associate_docstrings(Hashtbl.find(pre_table, pos));
  }
  catch (exn){
    if (exn === Caml_builtin_exceptions.not_found) {
      return /* () */0;
    } else {
      throw exn;
    }
  }
}

var post_table = Hashtbl.create(/* None */0, 50);

function set_post_docstrings(pos, dsl) {
  if (dsl !== /* [] */0) {
    return Hashtbl.add(post_table, pos, dsl);
  } else {
    return 0;
  }
}

function get_post_docs(pos) {
  try {
    var dsl = Hashtbl.find(post_table, pos);
    associate_docstrings(dsl);
    return get_docstring(/* false */0, dsl);
  }
  catch (exn){
    if (exn === Caml_builtin_exceptions.not_found) {
      return /* None */0;
    } else {
      throw exn;
    }
  }
}

function mark_post_docs(pos) {
  try {
    return associate_docstrings(Hashtbl.find(post_table, pos));
  }
  catch (exn){
    if (exn === Caml_builtin_exceptions.not_found) {
      return /* () */0;
    } else {
      throw exn;
    }
  }
}

function get_info(pos) {
  try {
    var dsl = Hashtbl.find(post_table, pos);
    return get_docstring(/* true */1, dsl);
  }
  catch (exn){
    if (exn === Caml_builtin_exceptions.not_found) {
      return /* None */0;
    } else {
      throw exn;
    }
  }
}

var floating_table = Hashtbl.create(/* None */0, 50);

function set_floating_docstrings(pos, dsl) {
  if (dsl !== /* [] */0) {
    return Hashtbl.add(floating_table, pos, dsl);
  } else {
    return 0;
  }
}

function get_text(pos) {
  try {
    return get_docstrings(Hashtbl.find(floating_table, pos));
  }
  catch (exn){
    if (exn === Caml_builtin_exceptions.not_found) {
      return /* [] */0;
    } else {
      throw exn;
    }
  }
}

var pre_extra_table = Hashtbl.create(/* None */0, 50);

function set_pre_extra_docstrings(pos, dsl) {
  if (dsl !== /* [] */0) {
    return Hashtbl.add(pre_extra_table, pos, dsl);
  } else {
    return 0;
  }
}

function get_pre_extra_text(pos) {
  try {
    return get_docstrings(Hashtbl.find(pre_extra_table, pos));
  }
  catch (exn){
    if (exn === Caml_builtin_exceptions.not_found) {
      return /* [] */0;
    } else {
      throw exn;
    }
  }
}

var post_extra_table = Hashtbl.create(/* None */0, 50);

function set_post_extra_docstrings(pos, dsl) {
  if (dsl !== /* [] */0) {
    return Hashtbl.add(post_extra_table, pos, dsl);
  } else {
    return 0;
  }
}

function get_post_extra_text(pos) {
  try {
    return get_docstrings(Hashtbl.find(post_extra_table, pos));
  }
  catch (exn){
    if (exn === Caml_builtin_exceptions.not_found) {
      return /* [] */0;
    } else {
      throw exn;
    }
  }
}

function symbol_docs() {
  return /* record */[
          /* docs_pre */get_pre_docs(Parsing.symbol_start_pos(/* () */0)),
          /* docs_post */get_post_docs(Parsing.symbol_end_pos(/* () */0))
        ];
}

function symbol_docs_lazy() {
  var p1 = Parsing.symbol_start_pos(/* () */0);
  var p2 = Parsing.symbol_end_pos(/* () */0);
  return Block.__(246, [(function () {
                return /* record */[
                        /* docs_pre */get_pre_docs(p1),
                        /* docs_post */get_post_docs(p2)
                      ];
              })]);
}

function rhs_docs(pos1, pos2) {
  return /* record */[
          /* docs_pre */get_pre_docs(Parsing.rhs_start_pos(pos1)),
          /* docs_post */get_post_docs(Parsing.rhs_end_pos(pos2))
        ];
}

function rhs_docs_lazy(pos1, pos2) {
  var p1 = Parsing.rhs_start_pos(pos1);
  var p2 = Parsing.rhs_end_pos(pos2);
  return Block.__(246, [(function () {
                return /* record */[
                        /* docs_pre */get_pre_docs(p1),
                        /* docs_post */get_post_docs(p2)
                      ];
              })]);
}

function mark_symbol_docs() {
  mark_pre_docs(Parsing.symbol_start_pos(/* () */0));
  return mark_post_docs(Parsing.symbol_end_pos(/* () */0));
}

function mark_rhs_docs(pos1, pos2) {
  mark_pre_docs(Parsing.rhs_start_pos(pos1));
  return mark_post_docs(Parsing.rhs_end_pos(pos2));
}

function symbol_info() {
  return get_info(Parsing.symbol_end_pos(/* () */0));
}

function rhs_info(pos) {
  return get_info(Parsing.rhs_end_pos(pos));
}

function symbol_text() {
  return get_text(Parsing.symbol_start_pos(/* () */0));
}

function symbol_text_lazy() {
  var pos = Parsing.symbol_start_pos(/* () */0);
  return Block.__(246, [(function () {
                return get_text(pos);
              })]);
}

function rhs_text(pos) {
  return get_text(Parsing.rhs_start_pos(pos));
}

function rhs_text_lazy(pos) {
  var pos$1 = Parsing.rhs_start_pos(pos);
  return Block.__(246, [(function () {
                return get_text(pos$1);
              })]);
}

function symbol_pre_extra_text() {
  return get_pre_extra_text(Parsing.symbol_start_pos(/* () */0));
}

function symbol_post_extra_text() {
  return get_post_extra_text(Parsing.symbol_end_pos(/* () */0));
}

function rhs_pre_extra_text(pos) {
  return get_pre_extra_text(Parsing.rhs_start_pos(pos));
}

function rhs_post_extra_text(pos) {
  return get_post_extra_text(Parsing.rhs_end_pos(pos));
}

function init() {
  docstrings[0] = /* [] */0;
  Hashtbl.reset(pre_table);
  Hashtbl.reset(post_table);
  Hashtbl.reset(floating_table);
  Hashtbl.reset(pre_extra_table);
  return Hashtbl.reset(post_extra_table);
}

var empty_docs = /* record */[
  /* docs_pre : None */0,
  /* docs_post : None */0
];

var empty_info = /* None */0;

var info_attr = docs_attr;

var empty_text = /* [] */0;

exports.init = init;
exports.warn_bad_docstrings = warn_bad_docstrings;
exports.docstring = docstring;
exports.docstring_body = docstring_body;
exports.docstring_loc = docstring_loc;
exports.set_pre_docstrings = set_pre_docstrings;
exports.set_post_docstrings = set_post_docstrings;
exports.set_floating_docstrings = set_floating_docstrings;
exports.set_pre_extra_docstrings = set_pre_extra_docstrings;
exports.set_post_extra_docstrings = set_post_extra_docstrings;
exports.empty_docs = empty_docs;
exports.docs_attr = docs_attr;
exports.add_docs_attrs = add_docs_attrs;
exports.symbol_docs = symbol_docs;
exports.symbol_docs_lazy = symbol_docs_lazy;
exports.rhs_docs = rhs_docs;
exports.rhs_docs_lazy = rhs_docs_lazy;
exports.mark_symbol_docs = mark_symbol_docs;
exports.mark_rhs_docs = mark_rhs_docs;
exports.empty_info = empty_info;
exports.info_attr = info_attr;
exports.add_info_attrs = add_info_attrs;
exports.symbol_info = symbol_info;
exports.rhs_info = rhs_info;
exports.empty_text = empty_text;
exports.text_attr = text_attr;
exports.add_text_attrs = add_text_attrs;
exports.symbol_text = symbol_text;
exports.symbol_text_lazy = symbol_text_lazy;
exports.rhs_text = rhs_text;
exports.rhs_text_lazy = rhs_text_lazy;
exports.symbol_pre_extra_text = symbol_pre_extra_text;
exports.symbol_post_extra_text = symbol_post_extra_text;
exports.rhs_pre_extra_text = rhs_pre_extra_text;
exports.rhs_post_extra_text = rhs_post_extra_text;
/* pre_table Not a pure module */
