// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


function h(state, param) {
  var value = param[/* value */0];
  if (typeof value === "number" || value.tag) {
    return state;
  } else {
    console.log(value[0]);
    return state;
  }
}

exports.h = h;
/* No side effect */
