// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var HandlePlainStatement$Jeason = require("./HandlePlainStatement.bs.js");

var mapper = HandlePlainStatement$Jeason.mapper;

exports.mapper = mapper;
/* No side effect */
