// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var HandleExpression$Jeason = require("./HandleExpression.bs.js");

function mapper(state, param) {
  var statement = param[1];
  if (typeof statement === "number" || statement.tag !== 18) {
    return state;
  } else {
    console.log("Var");
    var match = List.hd(statement[0][/* declarations */0]);
    var init = match[1][/* init */1];
    if (init) {
      return HandleExpression$Jeason.mapper(state, init[0]);
    } else {
      return state;
    }
  }
}

exports.mapper = mapper;
/* No side effect */
