// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var AstUtils$Jeason = require("./AstUtils.bs.js");
var Ast_helper$Jeason = require("../node_modules/bs-platform/vendor/ocaml/parsing/ast_helper.bs.js");

function transform(structureItems) {
  return List.map((function () {
                return Ast_helper$Jeason.Str[/* primitive */3](/* None */0, /* record */[
                            /* pval_name : record */[
                              /* txt */"make",
                              /* loc */Ast_helper$Jeason.default_loc[/* contents */0]
                            ],
                            /* pval_type : record */[
                              /* ptyp_desc : Ptyp_arrow */Block.__(1, [
                                  "",
                                  /* record */[
                                    /* ptyp_desc : Ptyp_constr */Block.__(3, [
                                        AstUtils$Jeason.astHelperStrLidIdent(/* None */0, /* :: */[
                                              "string",
                                              /* [] */0
                                            ]),
                                        /* [] */0
                                      ]),
                                    /* ptyp_loc */Ast_helper$Jeason.default_loc[/* contents */0],
                                    /* ptyp_attributes : [] */0
                                  ],
                                  /* record */[
                                    /* ptyp_desc : Ptyp_constr */Block.__(3, [
                                        AstUtils$Jeason.astHelperStrLidIdent(/* None */0, /* :: */[
                                              "nano",
                                              /* [] */0
                                            ]),
                                        /* [] */0
                                      ]),
                                    /* ptyp_loc */Ast_helper$Jeason.default_loc[/* contents */0],
                                    /* ptyp_attributes : [] */0
                                  ]
                                ]),
                              /* ptyp_loc */Ast_helper$Jeason.default_loc[/* contents */0],
                              /* ptyp_attributes : [] */0
                            ],
                            /* pval_prim : :: */[
                              "",
                              /* [] */0
                            ],
                            /* pval_attributes : :: */[
                              /* tuple */[
                                /* record */[
                                  /* txt */"bs.module",
                                  /* loc */Ast_helper$Jeason.default_loc[/* contents */0]
                                ],
                                /* PStr */Block.__(0, [/* [] */0])
                              ],
                              /* [] */0
                            ],
                            /* pval_loc */Ast_helper$Jeason.default_loc[/* contents */0]
                          ]);
              }), structureItems);
}

exports.transform = transform;
/* AstUtils-Jeason Not a pure module */
