// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_module = require("bs-platform/lib/js/caml_module.js");

var Literal = Caml_module.init_mod([
      "/Users/javi/Development/github/jeason/src/spider_monkey_ast.ml",
      39,
      6
    ], [[[[]]]]);

var Type = Caml_module.init_mod([
      "/Users/javi/Development/github/jeason/src/spider_monkey_ast.ml",
      205,
      6
    ], [[
        [[
            [[]],
            [[]]
          ]],
        [[
            [[]],
            [[]],
            [[]]
          ]],
        [[[[]]]],
        [[]],
        [[]],
        [[]],
        [[[[]]]],
        [[]],
        [[]]
      ]]);

var Statement = Caml_module.init_mod([
      "/Users/javi/Development/github/jeason/src/spider_monkey_ast.ml",
      506,
      6
    ], [[
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[[[]]]],
        [[]],
        [[]],
        [[[[]]]],
        [[[[]]]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[[[]]]],
        [[]],
        [[]],
        [[[[]]]],
        [[]]
      ]]);

var Expression = Caml_module.init_mod([
      "/Users/javi/Development/github/jeason/src/spider_monkey_ast.ml",
      772,
      6
    ], [[
        [[]],
        [[]],
        [[[[]]]],
        [[]],
        [[
            [[]],
            [[]]
          ]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[[[]]]],
        [[]],
        [[]],
        [[]]
      ]]);

var JSX = Caml_module.init_mod([
      "/Users/javi/Development/github/jeason/src/spider_monkey_ast.ml",
      875,
      6
    ], [[
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]]
      ]]);

var Pattern = Caml_module.init_mod([
      "/Users/javi/Development/github/jeason/src/spider_monkey_ast.ml",
      940,
      6
    ], [[
        [[
            [[]],
            [[]]
          ]],
        [[[[]]]],
        [[]],
        [[]]
      ]]);

var Class = Caml_module.init_mod([
      "/Users/javi/Development/github/jeason/src/spider_monkey_ast.ml",
      1000,
      6
    ], [[
        [[]],
        [[]],
        [[]],
        [[]]
      ]]);

var Function = Caml_module.init_mod([
      "/Users/javi/Development/github/jeason/src/spider_monkey_ast.ml",
      1023,
      6
    ], [[[[]]]]);

Caml_module.update_mod([[[[]]]], Literal, Literal);

Caml_module.update_mod([[
        [[
            [[]],
            [[]]
          ]],
        [[
            [[]],
            [[]],
            [[]]
          ]],
        [[[[]]]],
        [[]],
        [[]],
        [[]],
        [[[[]]]],
        [[]],
        [[]]
      ]], Type, Type);

Caml_module.update_mod([[
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[[[]]]],
        [[]],
        [[]],
        [[[[]]]],
        [[[[]]]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[[[]]]],
        [[]],
        [[]],
        [[[[]]]],
        [[]]
      ]], Statement, Statement);

Caml_module.update_mod([[
        [[]],
        [[]],
        [[[[]]]],
        [[]],
        [[
            [[]],
            [[]]
          ]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[[[]]]],
        [[]],
        [[]],
        [[]]
      ]], Expression, Expression);

Caml_module.update_mod([[
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[]]
      ]], JSX, JSX);

Caml_module.update_mod([[
        [[
            [[]],
            [[]]
          ]],
        [[[[]]]],
        [[]],
        [[]]
      ]], Pattern, Pattern);

Caml_module.update_mod([[
        [[]],
        [[]],
        [[]],
        [[]]
      ]], Class, Class);

Caml_module.update_mod([[[[]]]], Function, Function);

var Identifier = /* () */0;

var Variance = /* () */0;

var Comment = /* () */0;

exports.Identifier = Identifier;
exports.Literal = Literal;
exports.Variance = Variance;
exports.Type = Type;
exports.Statement = Statement;
exports.Expression = Expression;
exports.JSX = JSX;
exports.Pattern = Pattern;
exports.Comment = Comment;
exports.Class = Class;
exports.Function = Function;
/* Literal Not a pure module */
